chat-colors:
  # Cor para o nome do jogador e os colchetes que envolvem a tag do grupo.
  player-name: '&f'

  # Cor para o texto da tag do grupo.
  group-tag: '&b'
  
  # Cor padrao para a mensagem do chat.
  message: '&7'